apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs
    #app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      #app: microservices
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: karsajobs
        #app: microservices
    spec:
      containers:
      - image: jefriadisetiawan/karsajobsui:latest
        name: karsajobs-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: karsajobs-ui
        #env:
        #- name: API_URL
        #  value: http://192.168.49.2:31000

        
        #- name: VUE_APP_BACKEND
        #  value: http://192.168.49.2:31000
       