apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    #app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      #app: microservices
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: karsajobs
        #app: microservices
    spec:
      containers:
      - image: jefriadisetiawan/karsajobs:latest
        name: karsajobs
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGO_HOST
          value: mongodb-service
        #- name: MONGO_URL
          #value: mongodb://$(MONGODB-SERVICE_SERVICE_HOST):$(MONGODB-SERVICE_SERVICE_PORT_MONGODB-SERVICE)
          value: mongodb://mongodb-service:mongodb-service
        - name: APP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: karsajobs
      volumes:
      - name: mongodb-configmap
        configMap:
          name: mongodb-configmap
      - name: mongodb-secret
        secret:
          secretName: mongo-secret
     

          