apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    #app: microservices
spec:
  ports:
  - port: 8080
    #protocol: TCP 
    name: karsajobs-service
    targetPort: 8080
    #nodePort: 31000
  selector:
    app: karsajobs
    #app: microservices
  #type: NodePort
  type: ClusterIP
