apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  #credentials: |
  #  MONGO_INITDB_ROOT_USERNAME_FILE='/etc/credentials/MONGO_ROOT_USERNAME'
   # MONGO_INITDB_ROOT_PASSWORD_FILE='/etc/credentials/MONGO_ROOT_PASSWORD'
    