apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb-service
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb